"""empty message

Revision ID: 606402748899
Revises:
Create Date: 2024-05-16 17:44:18.444186

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "606402748899"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fullname", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_account_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_account_fullname"), ["fullname"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_account_id"), ["id"], unique=False)

    op.create_table(
        "board",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("board", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_board_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_board_name"), ["name"], unique=True)

    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("board_id", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["board.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_post_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_post_title"), ["title"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_title"))
        batch_op.drop_index(batch_op.f("ix_post_id"))

    op.drop_table("post")
    with op.batch_alter_table("board", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_board_name"))
        batch_op.drop_index(batch_op.f("ix_board_id"))

    op.drop_table("board")
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_id"))
        batch_op.drop_index(batch_op.f("ix_account_fullname"))
        batch_op.drop_index(batch_op.f("ix_account_email"))

    op.drop_table("account")
    # ### end Alembic commands ###
